# Generated by Django 3.2 on 2024-06-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle_name', models.CharField(max_length=50)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aisle', to='location.area')),
            ],
        ),
        migrations.CreateModel(
            name='Upright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upright_name', models.CharField(max_length=50)),
                ('aisle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upright', to='location.aisle')),
            ],
        ),
    ]
