# Generated by Django 3.2 on 2024-06-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last name')),
                ('username', models.EmailField(help_text='Username', max_length=254, null=True, unique=True, verbose_name='username')),
                ('email', models.EmailField(help_text='Email address', max_length=254, null=True, unique=True, verbose_name='Email Address')),
            ],
        ),
    ]
