# Generated by Django 3.2 on 2024-06-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, verbose_name='Item Name')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Sku')),
                ('upc_number', models.CharField(max_length=50, null=True, verbose_name='UPC Number')),
                ('cost', models.EmailField(max_length=254, null=True, verbose_name='cost')),
                ('description', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
            ],
        ),
    ]
